### ISSUE TITLE
Breakage of grunt angularjs build

### ISSUE THREAD

**Issue by pijalu** [cheeriojs/cheerio#1655]
Hi,

Recent update in cherrio broke older angularjs build due to cherrio 0.12.4 use in https://github.com/wmluke/grunt-inline-angular-templates. (cross post: https://github.com/wmluke/grunt-inline-angular-templates/issues/11)

Breakage is due to  "cheerio-select": "*" within package.json resulting in d/l of latest (and incompatible) cheerio-select.

A possible fix would be to fix the package.json on a new branch (0.12.5) 
cf proto-pr: https://github.com/cheeriojs/cheerio/pull/1654/commits/385ac9572373c9d1bd1816dfc1838a02a2e3f674

(Other 'manual" solutions included in grunt-inline-angular-templates ticket)

HtH

**Comment by 5saviahv** [comment]
you can install your own repo branch in npm by:
```
npm install git+https://github.com/pijalu/cheerio.git#0.12.4 --save
```

**Comment by pijalu** [comment]
Thank, but the point is to provide a clean solution for other that will likely suddenly see 'scratch build' failing out of the blue.

We fixed this in our own project by forcing a dev dep on cherrio-select@0.0.3 (cf issue logged at grunt-inline-angular-tempates) but it will likely touch other people with "older" code base (reason I log the issue / pr'ed)

Nota/bonus:
* For some reasons I don't get, shrinkwrap did not help (cherrio-select@0.0.3 is present in shrinkwrap but npm still d/l 1.0.0..) 
* I logged a similar issue on the grunt module as I suspect people will first go there... but the upstream is here :)

**Comment by 5saviahv** [comment]
sure best would be release cheerio 0.12.5 in npm with 0.0.3 cheerio-select

**Comment by Georgemanif** [comment]
I am facing the same issue...any news on this? Thank you

**Comment by pijalu** [comment]
> 
> 
> I am facing the same issue...any news on this? Thank you

For now, add to your project a dev dep on cherrio-select@0.0.3 
Unclean but will fix the problem until a clean solution is implemented ;)

**Comment by Georgemanif** [comment]
> > I am facing the same issue...any news on this? Thank you
> 
> For now, add to your project a dev dep on cherrio-select@0.0.3
> Unclean but will fix the problem until a clean solution is implemented ;)

Thank you for your answer, still doesn't work for me though....

**Comment by pijalu** [comment]
> 
> 
> > > I am facing the same issue...any news on this? Thank you
> > 
> > 
> > For now, add to your project a dev dep on cherrio-select@0.0.3
> > Unclean but will fix the problem until a clean solution is implemented ;)
> 
> Thank you for your answer, still doesn't work for me though....

hmm - that's odd as the 0,0.3 should stop the d/l of any other dep - just in case this is the part of my package.json
![image](https://user-images.githubusercontent.com/1093797/109292567-da381480-782a-11eb-848d-2824aef16851.png)
